---
- name: Create Datadog logging directories
  file:
    path: "/etc/datadog-agent/conf.d/{{ item }}.d/"
    state: directory
    mode: 0755
    owner: dd-agent
    group: dd-agent
  loop: "{{ sonar_log_names }}"
  tags:
    - datadog

- name: Create Datadog log config files.
  template:
    src: datadog-logs-config.yml
    dest: "/etc/datadog-agent/conf.d/{{ item }}.d/config.yaml"
    mode: 0755
    owner: dd-agent
    group: dd-agent
  loop: "{{ sonar_log_names }}"
  notify: restart datadog-agent
  tags:
    - datadog

- name: Create Datadog APM directory
  file:
    path: /opt/datadog-agent
    state: directory
    owner: dd-agent
    group: dd-agent
  tags:
    - datadog

- name: Download Datadog APM agent
  get_url:
    url: https://repo.dfw.rtrdc.net/rtr/global/dd-java-agent-0.33.0.jar
    dest: /opt/datadog-agent/dd-java-agent.jar
    validate_certs: no
  notify: restart sonar
  tags:
    - datadog

