---

# Memory configurations for SonarQube Enterprise

- name: Up number of files allowed to be open
  lineinfile:
    dest: "/etc/security/limits.conf"
    insertbefore: '^# End of file'
    line: "*               -       nofile           65535"

- name: Up number of processes allowed to be open
  lineinfile:
    dest: "/etc/security/limits.d/90-nproc.conf"
    regexp: ^(#?)\*\s*soft\s*nproc(.*)
    # Basically, match this line and its variations:
    # *          soft    nproc     1024
    line: "*          soft    nproc     4096"

- name: Up memory allocation
  lineinfile:
    dest: "/etc/sysctl.conf"
    line: "vm.max_map_count=262144"

- name: Reboot to load memory changes
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0

- name: Wait for the reboot to complete
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300
